#!/usr/bin/env python

import io
import json
import ftplib
import sys
from collections import defaultdict
from pkg_resources import parse_version

payload = json.load(sys.stdin)
source = payload['source']
version = payload.get('version')

with ftplib.FTP(source['host'], source['username'], source['password']) as ftp:
    ftp.cwd(source['channel_root'])
    with io.BytesIO() as fh:
        # TODO: Account for other archs
        try:
            ftp.size('noarch/repodata.json')
        except ftplib.error_perm:
            print('[]')
            sys.exit(0)
        ftp.retrbinary('RETR noarch/repodata.json', fh.write)
        repodata = json.loads(fh.getvalue().decode('utf-8'))

pkg_versions = defaultdict(set)
for package in repodata['packages'].values():
    pkg_versions[package['name']].add(package['version'])

versions = pkg_versions[source['package']]
sorted_versions = sorted(versions, key=parse_version)
if version is None:
    new_versions = [{'version': sorted_versions[-1]}]
else:
    version = version['version']
    try:
        i = sorted_versions.index(version)
    except ValueError:
        new_versions = [{'version': sorted_versions[-1]}]
    else:
        new_versions = [{'version': x} for x in sorted_versions[i:]]

# Concourse is expecting to see this in stdout
print(json.dumps(new_versions))
