---
jobs:
  - name: stage-q2-no-op
    public: true
    plan:
      - get: q2-no-op-test-channel
        trigger: true
      - put: q2-no-op-staging-channel
        params:
          from: q2-no-op-test-channel

resources:
  - name: q2-no-op-test-channel
    type: conda-channel
    check_every: 1m
    source:
      pkg_name: q2-no-op
      channel: test1
      uri: ftp://testing-channel-ftp
      user: test1
      pass: password

  - name: q2-no-op-staging-channel
    type: conda-channel
    check_every: 1m
    source:
      pkg_name: q2-no-op
      channel: test1
      uri: ftp://staging-channel-ftp
      user: test1
      pass: password

resource_types:
  - name: conda-channel
    type: docker-image
    source:
      repository: quay.io/qiime2/conda-channel-resource
